hash-format = "sha256"

[[files]]
file = "mods/accessories-cc-layer.pw.toml"
hash = "d84961fe65fcb7f4da1689bdc7a1f1b8ce751a2b1eff2b18fb1f5c8027d22042"
metafile = true

[[files]]
file = "mods/accessories.pw.toml"
hash = "5d3f94d4280b3367a376f086018a4005866ddecbe80b6abb0849e5d995a98e9d"
metafile = true

[[files]]
file = "mods/alltheleaks.pw.toml"
hash = "7d83338d2e5a1c0f153c08901f9e84fa711bb4a2bfca54e93667d76705b707fe"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "8d0321177fed4a0b48554c40158b43db62f6cdaa768f584ef6a11575dfaa6223"
metafile = true

[[files]]
file = "mods/applied-energistics-2.pw.toml"
hash = "0f4c2198603cd84a14dc6741729d0b0dcf509574776e620c36c3e7180082db32"
metafile = true

[[files]]
file = "mods/applied-mekanistics.pw.toml"
hash = "e86f6cb8be0b72ee9920dd3745fec63eb46300d06ae78e3beb5a08dedc8ed46b"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "5e9edd1fd2395f14a0c8a4acbdbdd61e1047be1f0033deb3140d2ce0d093e9d8"
metafile = true

[[files]]
file = "mods/armored-paws-backport.pw.toml"
hash = "2da9bbe040e4466b67697f283667fb7de757f0de316182f2b3aeeaba56c74c20"
metafile = true

[[files]]
file = "mods/ars-elemental.pw.toml"
hash = "edf6b8a4b3daa8579920fd7d4bcf08898465eab1c31f8906f8bf3bba1bdda84a"
metafile = true

[[files]]
file = "mods/ars-energistique.pw.toml"
hash = "fe693ae80d95c3b06c0c91285417bf58d13e1e1d69496d35224dbf0002d54476"
metafile = true

[[files]]
file = "mods/ars-nouveau.pw.toml"
hash = "44505ec6c8d7ac5948b3f192cff3db191b07c4d39d501ce3af916006cda3c5a6"
metafile = true

[[files]]
file = "mods/ars-technica.pw.toml"
hash = "f74d674d172fb27b93f1738f092a2d6b2d4cecc578656f9357886b8e13fecc35"
metafile = true

[[files]]
file = "mods/athena.pw.toml"
hash = "9638d8a308563842fd989970919a51f37ed1bcc82372bff47fc5a5c2e6de738e"
metafile = true

[[files]]
file = "mods/bclib.pw.toml"
hash = "0c6982d793283b27ef35fdc3b57b7b9554fbc162c03ac7431ebbee9b1d5b241c"
metafile = true

[[files]]
file = "mods/better-spawner-control.pw.toml"
hash = "33c69c0eada517ef46d742e90bf21c69426f04da91d034f45c82de0b5e0ac904"
metafile = true

[[files]]
file = "mods/betterend.pw.toml"
hash = "4b8ffbe47270effb2da83ff2fba6e5dea0158a515033b61a484a21aae6146a76"
metafile = true

[[files]]
file = "mods/betternether.pw.toml"
hash = "f04f6619202e8b2b22e33c4ce152f879633577d82ada897327603c050da601df"
metafile = true

[[files]]
file = "mods/blood-magic.pw.toml"
hash = "488623331de35d0132795aeb028cca441fc0d5c2e358faf25e973894fb3859a7"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
hash = "da069e723737ae49203f7572eb774be0fd21f5f083ce7a7ee1bed25916befca8"
metafile = true

[[files]]
file = "mods/carbon-config.pw.toml"
hash = "2113d7b7832ae7bb08781cccec670a81fd6d7a5c2e6758ef73f58b7f423218b2"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "71a33fe41bead909b3e95643351ef8015def70d3cb083916469f492f66434b45"
metafile = true

[[files]]
file = "mods/chunkpregenerator.pw.toml"
hash = "b00ef25575c34bcb493300d62abcbd5ee53859186c729b9fd2d0c5588e2dd849"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "96204145e12506e0625d8b9bfa05aad54e9a62fd511bae39f0d57fcb5e39f4cc"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "e3173aaa4e9078ad7ace2b9ef43ce15ce9919c0b566d8830cea87264f92b3a6a"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "492359a6ce93fbf09eb6e1d20b761a5538fe9197e7d129949234d83b87e06bc1"
metafile = true

[[files]]
file = "mods/connector-extras.pw.toml"
hash = "ccc22ae710d22b2c8e8851c5968f85d32bac9f40ee7ded717df78cbe0cc8dae3"
metafile = true

[[files]]
file = "mods/copper-tuff-backport-fabric.pw.toml"
hash = "f0db554ba12092ebd6501684fda5de1122bd7cdc5189ba77a7daa0b6e9d63d37"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "4123cb2c965568652799530427cdd9e94b5f6f463ba3a8e92b715ef7b0ed10eb"
metafile = true

[[files]]
file = "mods/corgilib.pw.toml"
hash = "28053b4a334c4079b5d4c7ea2d3b8d48f8fa61420498f1bed0ff83cd316bbba0"
metafile = true

[[files]]
file = "mods/cosmetic-armor-reworked.pw.toml"
hash = "cfa8aa9c0437721dab2057c932c9cf8ec3d3a11f672040601305238d13df85e8"
metafile = true

[[files]]
file = "mods/create-applied-kinetics.pw.toml"
hash = "013dea4c4202116e4e1382b99d984d3af25f817bd04be2cf6573b59f2affab90"
metafile = true

[[files]]
file = "mods/create-big-cannons.pw.toml"
hash = "a92288574aeb3b2387d8c423b980321efa0f486074d6167aa30195a09d930369"
metafile = true

[[files]]
file = "mods/create-connected.pw.toml"
hash = "31388efced2f1d0bc3c5801a77649069093cdeadeaffbaccf9e829a01bd22581"
metafile = true

[[files]]
file = "mods/create-oh-the-biomes-weve-gone-compat.pw.toml"
hash = "31f269762ab620d579996000d83d4c66d2e7f8a989b408afe3b9015f068984bb"
metafile = true

[[files]]
file = "mods/create-radars.pw.toml"
hash = "d827f46b0bdd2fb7132d48709a20ee19fbb9d950ec418c77d4d92711289de7e5"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "ffdbe21062b94ead8032249a95072bd9c2511e723d0a205066d34fdb6060fff9"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "9d7971a7af2ff4a96a0e5aede76f9cf8dc978da601e2754f79d6ec8631125bb9"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "8a5f33277995fccd2be6793c4fba1b5d657983be32f0b47e4afab4eac70b8ab8"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "51840d820bafb365a53a064f1ef3d4bdeff4059d0a720bb02315686d3f7b0f7e"
metafile = true

[[files]]
file = "mods/decorative-blocks.pw.toml"
hash = "02e3f47ff5a2fa074996387e14c81718e5c4df16dbe75ba1e1021157352f7815"
metafile = true

[[files]]
file = "mods/deltaboxlib.pw.toml"
hash = "ad59bde8d2371eae2a5f98741da8d1018496426147d63a7f5db028d3ccb45212"
metafile = true

[[files]]
file = "mods/dynamiclights-reforged.pw.toml"
hash = "8f2270a50a633db681826cbfb691e6efdb25e1e0c4702125c13d525b52fe229f"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "a1575677daaaf6ea6dac12e5a10073e34025e5ca2c35b6d36ad4a5a0edbc0e82"
metafile = true

[[files]]
file = "mods/explorers-compass.pw.toml"
hash = "0ba2a01934d2de588071ac5a5281dd9a29fc46166fe6b9f99a809a70fe1a6668"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "5bd0506bc0be25116b234f2b5af9447f60d82ae1cb6c5be4e12d8841f6c2501c"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "62ef7e92478035b77e996189984e4749b2d876ed0a389977a2670a28f105bfd2"
metafile = true

[[files]]
file = "mods/friends-and-foes-forge.pw.toml"
hash = "a6b8531e7b13bf3d480a01d4f79612ac60a3a83d461e402360e1d223dbd5bcec"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "88f142bda6bfa6aff4f4d4e12b8ba7581aa40e3f163039a533f09dd6d634e093"
metafile = true

[[files]]
file = "mods/geophilic-backport-vanilla-backport-compact.pw.toml"
hash = "9ac29f29b7060db1aa2c0f71e0caad394243c777ce9657ea146836bee518b95c"
metafile = true

[[files]]
file = "mods/guideme.pw.toml"
hash = "5cc92eb0e58c2afbfd625d727d80da1d1c84500ec962bb22f5be28b864f18551"
metafile = true

[[files]]
file = "mods/iav.pw.toml"
hash = "8c4faf1ccc0cf72cb9d52b6fd439a63723d30c951db71508a94973cd8da97e10"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
hash = "82f389d06c0e19d2ffcd75d5d85e0d9f09ec17178b8dd3e5afe9350a271e0443"
metafile = true

[[files]]
file = "mods/immersive-engineering.pw.toml"
hash = "6439c6f409308c4a89a12708b54cef41aa5382dc78e6f352b3e8005e96a21a8e"
metafile = true

[[files]]
file = "mods/immersive-fixes.pw.toml"
hash = "20c92a04cd424ae11964dd5275a110411408c10157c2b43f3577b089485c6e93"
metafile = true

[[files]]
file = "mods/immersive-lanterns.pw.toml"
hash = "ae3f14983e2a8ff5d133b6d665f667c9b23f2f124f63cb634503c6413da1cab8"
metafile = true

[[files]]
file = "mods/immersive-machinery.pw.toml"
hash = "abf30f9ed0ce36e9df7b1e9d57a29a31d1302168c50bdfa1e2f47cf05ff60c95"
metafile = true

[[files]]
file = "mods/immersive-petroleum.pw.toml"
hash = "545bce984d1bc4f34794a2506be3250e69356ad270d90a86d1b38f6e1d4ccb34"
metafile = true

[[files]]
file = "mods/immersiveposts.pw.toml"
hash = "ac84a3cb33afe375bceaf3aae16fd52e43e8f35e9f4bded4841778cb33b3a367"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "8f359d190506a6f824763b8e7c390d9e22204ef11e3ffa5ef980000d17e2c2b6"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "5f7c3cf35124bf96e880cc8562fc44ac15990a89b07db299aed9a88ce3752cb1"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "40026875ee9b7d25a4ece48faa2b70a338100e87a689d5a8d4ba1ee608b878f6"
metafile = true

[[files]]
file = "mods/mekanism-generators.pw.toml"
hash = "a76a1f1d2139ebe5c31c628ed4bb01f3795cfae931dda4093047260507bbfd43"
metafile = true

[[files]]
file = "mods/mekanism-turrets-fences.pw.toml"
hash = "c16b8b221ea0dfec37d54236836b211eef3a3e03843b033d63d9aa24679adf4f"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
hash = "7c411a566d022680769ddb8323984fff292ddeb35e7d8fcfe2cc41b9885d9557"
metafile = true

[[files]]
file = "mods/minecraft-transport-simulator.pw.toml"
hash = "067a6968ac97746dd514a02fa51fbffdff4ebce3125b0971de537bc099b82fea"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "373b18020e519fa602dc3e5ecc7d9d1523a353ddec85b20fe8dbbad23d4e7db2"
metafile = true

[[files]]
file = "mods/more-immersive-wires.pw.toml"
hash = "5852a96f18ca4c2edc81e5755c4aeece7203a742723d023918a57c82bfba658b"
metafile = true

[[files]]
file = "mods/more-mekanism-processing.pw.toml"
hash = "c6501084f865ed2a47bcd0a7fb1d8d5bdbce7ce300642c034c4cb184609b0a38"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "464e83a35e22e9bbdf7be38cf7a7a98c39462a0a50b01d2a1355bcae9167ea7a"
metafile = true

[[files]]
file = "mods/nocubes-better-blast-furnace.pw.toml"
hash = "ef576468ebecc313ae540a9380542f9760af5ce412a0a16bad79919fa7942dcd"
metafile = true

[[files]]
file = "mods/nocubes-better-fletching-table.pw.toml"
hash = "5238e1560a88073e52f961c66ac9bb688c009580c784943fefcc02a52530af8b"
metafile = true

[[files]]
file = "mods/nocubes-better-grindstone.pw.toml"
hash = "fb34279782af3594a669f97c721594165b56b6fa7b2c92aa0141276b6bddaae8"
metafile = true

[[files]]
file = "mods/ob-aquamirae.pw.toml"
hash = "caf733526eccac9b26d70b2649d5fa99d832d16a2379a9aa2515049c77765077"
metafile = true

[[files]]
file = "mods/obscure-api.pw.toml"
hash = "96008b869b133a400c97313afa460bda3b4d43aeddcafaf04c4141f9193f3095"
metafile = true

[[files]]
file = "mods/octo-lib.pw.toml"
hash = "320c4d3a50b1f2f45d64d2f88c8c16473bc85b95d67e54ff93205ac9d2ead3cf"
metafile = true

[[files]]
file = "mods/oh-the-biomes-weve-gone.pw.toml"
hash = "31656203172b1ecf76e38e9d957dba3694a15b7972dd49eea49c7b61c19d70c4"
metafile = true

[[files]]
file = "mods/oh-the-trees-youll-grow.pw.toml"
hash = "060967c337239159637dc07818af3020eb7c323102fe21f4171645c030e3fec7"
metafile = true

[[files]]
file = "mods/origins-backgrounds-forge.pw.toml"
hash = "8dc27fa909f93850e85f7b58f701cb4f6a51e1012325bdd739ee0be6031bd3b2"
metafile = true

[[files]]
file = "mods/origins-classes-forge.pw.toml"
hash = "8bcac14e9d9de7789277a7c48b7c05c3f79618dfee5c6e7002c165dfcdae58f2"
metafile = true

[[files]]
file = "mods/origins-forge.pw.toml"
hash = "cb91a483997feae40c3edfc9d5a06dc44fdf2f562a62f065834e9e1a6a1c7f8f"
metafile = true

[[files]]
file = "mods/origins-more-backgrounds.pw.toml"
hash = "225aa1d0150b18f461c56cdea615bc2b36faf884109e58250d00f689398995b1"
metafile = true

[[files]]
file = "mods/origins-plus-plus.pw.toml"
hash = "ecb3696cd171e3a5fb199ad2715b3780e3f9ec5439c16b466927fcbcb51f8d0e"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "e3b879b027674a3c9b002eb24f2ea47397bf2087124387f65241b4e0ca4e73d5"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "dec2bc011d4ca1d451aaa3eea477f13366bfb13beba0716018f47d9331a50d8e"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
hash = "ff455d3439b8e4ffbf78dc1e8998c1b59200bd10c74c77f9fe90e98f606e0f0d"
metafile = true

[[files]]
file = "mods/relics-mod.pw.toml"
hash = "25609a67855ca325666450932d91a06e1b8684be8f2d0e1f1a36fd0febf49848"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "ef0264b7d819848f72ab2f34643306187e712965a8246e1f733e1bd39d8fd681"
metafile = true

[[files]]
file = "mods/ritchies-projectile-library.pw.toml"
hash = "8206df6c97f3b0696ca143240084eea614dc1f404ab917dde9c5f156cebafa02"
metafile = true

[[files]]
file = "mods/sinytra-connector.pw.toml"
hash = "0eab5a7036d1f06d6a7d4679685eaec5723a5c21469f519de1cd1e0ff416ade3"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "5240c62752415b5d66d4beffec4fe98c253eba8ebcbb2a5c1097fc3ad3de0b00"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-create-integration.pw.toml"
hash = "0462f0b658c766e1ccb9974f576090713738606d6513aba89cf8d5ba2b00847b"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "3bb4a9500b84afbceb8d426505a1727888aa53de23f839ce261fe6956491cc83"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "4e0171baa817919422b027a64d97ef8ffc63879c94671b2fc42f191cc6f3900d"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "fde3d3b1607636100e382dce1bba80ab4608ebfa1ef888a37b86bc8c7dcbafe5"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "b0978cb7ae7b79c5be89b323ca1bd038f693ff6d11c43dfcbd63953964149af2"
metafile = true

[[files]]
file = "mods/tome-of-blood-rebirth.pw.toml"
hash = "5dccfff265f9a6c8a38a46a09d2034617045588671af2ea04b6ffe922b469506"
metafile = true

[[files]]
file = "mods/transport-simulator-official-vehicle-set.pw.toml"
hash = "70e3f044e97ac4eefca113fa888fde8bb0e341481f7fb539c69153baa55bc88d"
metafile = true

[[files]]
file = "mods/txnilib.pw.toml"
hash = "7149b1beafef2ce275da37dd5ca2e12f5527ad979420630ecdef5bcabd4fef32"
metafile = true

[[files]]
file = "mods/vanillabackport.pw.toml"
hash = "4d70c171b0fe3efba1ab55419484a58446b492a472034a2508c7de5a3f9e8272"
metafile = true

[[files]]
file = "mods/veb-aws.pw.toml"
hash = "2e6c0349d94839024ec211a6792aee006b5e43dbbdc22308ccddf55e43e3227d"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "eb48e8709268d9d4daeaba8d8844fa47e4e42fe2c6767ab39eca10e7852abf1e"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "8c1d85564af53d61caf23b502b60c494d33450a670093fdd3e2f412368682ecc"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "9fb6a1a06b18f2ce7b0811200339d997925cb39bde220fbaea4d5c8067376c12"
metafile = true

[[files]]
file = "mods/yungs-better-caves.pw.toml"
hash = "c6d1c3ab24396c5efd9c0bfa4eeedd9c8c42fe9be329de55d25b299f1e9ea0a2"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "58148fa22c72e0b0eac5e35fed0be9194ad59fe848298c1b61b565fa3158b2f4"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "31fca121c5b55c624ed203937c8f9b4d13cfe32f80bb85405aa4c65238378b15"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "a5af976bf45b8e0aaaa22bebb11504ef0687e90d2cff9d3fa3b648c0757c1446"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts-forge.pw.toml"
hash = "e0d77569aa19c6b72d30cb895cef575837a5740bee489d3ae537edf40a900ab1"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "18e0db08323413e9ad0c0959ca71d700f72a53dcd9fa5eb368cacc62c65168db"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "f58f817a74f2b26fca9922263bf3f616deb0ee709212aa944ece857bf47a2d6e"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "32d07d192caa9459521c3b3bc21199ebe72d7f6cad9b3461e0b231180f46bb30"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "2eb3e909cc46e39d8b9e762f39c36b0579744118d619beb6a174d264951d6248"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
hash = "f664d8e9753262b287d5cf1be3d17a59d01b7f8293b91db335adcc2cae5e2f55"
metafile = true

[[files]]
file = "mods/yungs-cave-biomes.pw.toml"
hash = "2c300c8f7129aabbfd0a5d913edd31baf1ee2641907d220ccc6981a6be204432"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
hash = "aedb648ee15bdb7bb3af23cfa4ad565c0fe531f62e89406566bec90659be9a42"
metafile = true
