name = "mc.skynetworks.cc SERVER"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5157159cc9fcaf29223e582623d546c4217c5f7e4bfa397ce5f4db3f5cc4bf2"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
